name: ci

on:
  push:
    branches:
      - "release"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_KEY }}'  
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 'Create env file'
        run: |
          touch .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          cat .env
      -
        name: Set up Docker Buildx
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      -
        name: Pull Docker Image
        run: docker pull tuananhhmx4/clockbox:latest
      -
        name: Run Docker Container
        run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
        # run: docker images
